import express from "express";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pdfParse from "pdf-parse";

dotenv.config();
const app = express();
const port = process.env.PORT || 3000;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PDF_URLS = ["https://arpitsrivastava.co.in/resources/Kawach%20Madule.pdf","https://arpitsrivastava.co.in/resources/Meena%20munch%20module.pdf","https://arpitsrivastava.co.in/resources/CWPC%20Strengthening%20and%20Activation%20Process%20Document.pdf","https://arpitsrivastava.co.in/resources/Bal%20sanrakshan%2010-03-2026%20(1).pdf","https://arpitsrivastava.co.in/resources/SHG%20Module.pdf","https://arpitsrivastava.co.in/resources/Yojana%20Module%2004-26.pdf","https://arpitsrivastava.co.in/resources/Child-Trafficking-Resource.pdf"];
const textKnowledgePath = path.join(__dirname, "knowledge.txt");
let documents = [], chunks = [], pdfCount = 0;
function normalizeText(text){return String(text||"").replace(/\r/g,"").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();}
function makeChunks(text,size=1400,overlap=250){const clean=normalizeText(text),result=[];let start=0;while(start<clean.length){let end=Math.min(start+size,clean.length);if(end<clean.length){const boundary=Math.max(clean.lastIndexOf("\n\n",end),clean.lastIndexOf(". ",end),clean.lastIndexOf(" ",end));if(boundary>start+Math.floor(size*.6))end=boundary+1;}result.push(clean.slice(start,end).trim());if(end>=clean.length)break;start=Math.max(end-overlap,start+1);}return result.filter(Boolean);}
async function loadPdfFromUrl(url){const response=await fetch(url,{redirect:"follow"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const buffer=Buffer.from(await response.arrayBuffer());const pdf=await pdfParse(buffer);return {text:normalizeText(pdf.text),pages:pdf.numpages||0};}
async function loadKnowledgeBase(){documents=[];chunks=[];pdfCount=0;try{if(fs.existsSync(textKnowledgePath)){const text=normalizeText(fs.readFileSync(textKnowledgePath,"utf8"));if(text)documents.push({name:"knowledge.txt",text});}}catch(error){console.error("knowledge.txt error:",error.message);}for(const url of PDF_URLS){const name=decodeURIComponent(url.split("/").pop());try{const result=await loadPdfFromUrl(url);if(!result.text){console.warn(`No readable text: ${name}`);continue;}documents.push({name,text:result.text,url,pages:result.pages});pdfCount++;console.log(`PDF loaded: ${name} | pages=${result.pages} | chars=${result.text.length}`);}catch(error){console.error(`PDF failed: ${name} | ${error.message}`);}}for(const doc of documents){for(const text of makeChunks(doc.text))chunks.push({source:doc.name,url:doc.url||null,text});}console.log(`Knowledge base ready: ${pdfCount} PDFs, ${chunks.length} searchable chunks.`);}
const STOP_WORDS=new Set(["the","and","for","are","what","how","why","with","from","this","that","can","does","about","according","please","tell","give","kya","hai","ka","ki","ke","ko","me","mein","se","aur","par","ya","hain","kaise","kiski","kiske","kis"]);
function tokenize(text){return normalizeText(text).toLowerCase().replace(/[^a-z0-9\u0900-\u097f\s]/gi," ").split(/\s+/).filter(w=>w.length>=2&&!STOP_WORDS.has(w));}
function searchChunks(question){const q=normalizeText(question).toLowerCase();const queryTokens=[...new Set(tokenize(question))];const wantsMeena=/meena\s*manch|meena\s*munch|मीना\s*मंच/i.test(q);const wantsCWPC=/cwpc/i.test(q);const wantsKawach=/kawach|कवच/i.test(q);const wantsTraffic=/child\s*trafficking|trafficking|तस्करी/i.test(q);if(!queryTokens.length&&!wantsMeena&&!wantsCWPC&&!wantsKawach&&!wantsTraffic)return chunks.slice(0,5);const ranked=chunks.map(chunk=>{const text=chunk.text.toLowerCase(),source=chunk.source.toLowerCase();let score=0;const phrases=[...(wantsMeena?["meena manch","meena munch","मीना मंच"]:[]),...(wantsCWPC?["cwpc","child welfare and protection committee","child protection committee"]:[]),...(wantsKawach?["kawach","कवच"]:[]),...(wantsTraffic?["child trafficking","trafficking","बाल तस्करी","तस्करी"]:[])];for(const phrase of phrases){if(text.includes(phrase))score+=18;if(source.includes(phrase))score+=30;}if(wantsMeena&&/meena/i.test(source))score+=100;for(const token of queryTokens){let count=0,pos=0;while((pos=text.indexOf(token,pos))!==-1){count++;pos+=token.length;if(count>=5)break;}score+=Math.min(count,5)*2;if(text.includes(token))score+=4;}score+=queryTokens.filter(t=>text.includes(t)).length*3;return {...chunk,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(wantsMeena){const meena=ranked.filter(x=>/meena\s*(munch|manch)/i.test(x.source)),rest=ranked.filter(x=>!/meena\s*(munch|manch)/i.test(x.source));return [...meena,...rest].slice(0,5);}return ranked.slice(0,5);}
if(!process.env.GEMINI_API_KEY)console.warn("WARNING: GEMINI_API_KEY is not configured.");
const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});
const baseInstructions=`You are KAWACH Child Protection Chatbot for children and adolescents in India.\n\nMANDATORY FORMAT:\nEnglish:\n[Simple, clear English answer]\n\nHindi:\n[Same answer in simple Hindi]\n\nSOURCE ACCURACY RULES:\n- Supplied PDF excerpts are the primary factual source.\n- Preserve exact terminology, acronym expansion, names, roles and titles used in the excerpts.\n- NEVER guess or expand an acronym from general knowledge.\n- When the user names a resource such as Meena Manch, KAWACH, CWPC, Child Trafficking, SHG or Yojana, prioritize that named PDF/source.\n- Answer from retrieved excerpts, not general memory.\n- Do not combine unrelated PDFs merely because they contain similar words.\n- If excerpts do not support a fact, say: I cannot verify this specific information from the available KAWACH resources.\n- Do not invent facts, laws, sections, penalties, procedures, contacts or government claims.\n- Keep answers concise and relevant.\n\nSAFETY:\n- Immediate danger: move to a safe place, contact a trusted adult, 112 for emergency help and 1098 Child Helpline.\n- Never ask for passwords, OTPs, Aadhaar, bank details, exact home address or unnecessary identifying information.\n- Never promise secrecy. Do not blame, shame, threaten or pressure a child.\n- For sexual abuse, trafficking, violence, child marriage, child labour, exploitation, neglect, missing children, online safety or self-harm, prioritize safety and real-world support.\n- If self-harm/suicide is mentioned, encourage immediate trusted-adult/emergency support and never provide methods.\n- Legal answers are general information, not legal advice.\n- Be calm, respectful, child-friendly and non-judgmental.`;
app.use(express.json({limit:"32kb"}));app.use(express.static(__dirname));app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.get("/health",(req,res)=>res.json({status:"ok",service:"KAWACH Child Protection Chatbot",ai:"Gemini",pdfKnowledgeBase:pdfCount>0?"loaded":"no PDFs loaded",pdfCount,searchableChunks:chunks.length}));
app.get("/api/knowledge-status",(req,res)=>res.json({status:"ok",pdfCount,searchableChunks:chunks.length,sources:documents.map(d=>d.name)}));
async function generateGeminiResponse(message){const relevant=searchChunks(message);const context=relevant.length?relevant.map((item,i)=>`SOURCE ${i+1}: ${item.source}\n${item.text}`).join("\n\n---\n\n"):"No relevant PDF excerpt was found.";const systemInstruction=`${baseInstructions}\n\nRELEVANT RESOURCE EXCERPTS:\n${context}\n\nEND RESOURCE EXCERPTS.`;const models=[{name:"gemini-3.5-flash-lite",thinkingLevel:"minimal"},{name:"gemini-3.6-flash",thinkingLevel:"minimal"}];let lastError=null;for(const model of models){try{console.log(`Trying fast model: ${model.name}`);const response=await ai.models.generateContent({model:model.name,contents:message,config:{systemInstruction,maxOutputTokens:700,thinkingConfig:{thinkingLevel:model.thinkingLevel}}});return response.text||"No response was generated.";}catch(error){lastError=error;console.error(`Gemini error | ${model.name}:`,error?.message||error);}}throw lastError;}
app.post("/api/chat",async(req,res)=>{try{const message=String(req.body?.message||"").trim();if(!message)return res.status(400).json({error:"Please enter a question."});if(message.length>4000)return res.status(400).json({error:"Question is too long. Please keep it under 4000 characters."});if(!process.env.GEMINI_API_KEY)return res.status(503).json({error:"AI service is not configured yet."});const answer=await generateGeminiResponse(message);return res.json({answer});}catch(error){console.error("KAWACH FINAL ERROR:",error?.message||error);return res.status(503).json({error:"KAWACH is temporarily busy. Please try again in a few seconds. If you need immediate help, contact 1098 or 112."});}});
app.use((req,res)=>res.status(404).json({error:"Page or API endpoint not found."}));
async function startServer(){await loadKnowledgeBase();app.listen(port,"0.0.0.0",()=>{console.log(`KAWACH running on port ${port}`);console.log(`PDF Knowledge Base: ${pdfCount} PDF(s)`);console.log(`Searchable chunks: ${chunks.length}`);});}
startServer().catch(error=>{console.error("KAWACH SERVER START ERROR:",error);process.exit(1);});